Description: >
  Heba Ghazaly / Bastion Host

Parameters:
  EnvName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  AMI:
    Description: AMI to use for our base image
    Type: String
  InstanceType:
    Description: The EC2 instance type
    Type: String

Resources:
  BastionSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to bastion host
      VpcId:
        Fn::ImportValue: !Sub '${EnvName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 102.40.151.145/32 # use your public IP address
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      KeyName: jumpbox-key
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet:
            - Ref: 'BastionSecGroup'
          SubnetId:
            Fn::ImportValue: !Sub '${EnvName}-PUB1-SN'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
